#!/usr/bin/env ruby

require 'rbbt-util'
require 'rbbt/util/simpleopt'

$0 = "rbbt #{$previous_commands*" "} #{ File.basename(__FILE__) }" if $previous_commands

options = SOPT.setup <<EOF

Description

$ #{$0} [options] <filename.vcf>  <filename.vcf>  [<filename.vcf>] 

-h--help Print this help

EOF
if options[:help]
  if defined? rbbt_usage
    rbbt_usage 
  else
    puts SOPT.doc
  end
  exit 0
end


files = {} 
ARGV.each do |key|
  name, file = key.split(":")
  files[name] = file
end


Workflow.require_workflow "HTS"

puts HTS.combine_caller_vcfs(files)
