#!/bin/bash

name='HISAT'
url="https://cloud.biohpc.swmed.edu/index.php/s/fE9QCsX3NH4QwBi/download"

prepare_pkg "$name" "$url"
rm `build_dir`/CMakeLists.txt # Force regular make compilation to make it work in STARLIFE
build "$name"
