#!/bin/bash

name='Strelka'
url="https://github.com/Illumina/strelka.git"

unset CPLUS_INCLUDE_PATH LIBRARY_PATH LD_LIBRARY_PATH C_INCLUDE_PATH LD_RUN_PATH PKG_CONFIG_PATH
install_git "$name" "$url" 
